version: "3.8" 
services: 
  database: 
    image: postgres:13 
    environment: 
      POSTGRES_DB: sac_control 
      POSTGRES_USER: sac_user 
      POSTGRES_PASSWORD: sac_password_2024 
    ports: 
      - "5432:5432" 
    volumes: 
      - postgres_/var/lib/postgresql/data 
    networks: 
      - sac_network 
  redis: 
    image: redis:6 
    ports: 
      - "6379:6379" 
    networks: 
      - sac_network 
  adminer: 
    image: adminer 
    ports: 
      - "8080:8080" 
    networks: 
      - sac_network 
volumes: 
  postgres_: 
networks: 
  sac_network: 
    driver: bridge 
